### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Repooc** [elvador/wow-spell-tooltips#1]
Documentation on file format of the csv and or source of the spell data would be nice to help you keep this package updated... This would be some tedious work to do by hand so I assume you had a way to dump the data or something from somewhere.

Sorry for making a ticket to ask you this as there isn't any contact info and I knew this is more likely to be seen by you.

**Comment by elvador** [comment]
I've shared the addon I use to export the data here:
https://github.com/elvador/SpellExport

**Comment by Repooc** [comment]
Thank you and sorry for any bother.  Appreciate the quick response.

**Comment by elvador** [comment]
No worries. I wanted to do this since forever, your post finally made me do it :wink:
